### ISSUE TITLE
GNU std target

### ISSUE THREAD

**Issue by polluks** [Un1q32/uniqlibc#1]
How about _check_?
https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html
https://github.com/Un1q32/uniqs-darwin-libc/blob/b2844bfe2a6c86d5e44a0cd175c4514a9968adaf/Makefile#L40

**Comment by Un1q32** [comment]
```
‘check’
Perform self-tests (if any). The user must build the program before running the tests, but need not install the program; you should write the self-tests so that they work when the program is built but not installed.

The following targets are suggested as conventional names, for programs in which they are useful.
```

the `tests` target doesn't run any tests, it just builds and links them.
