### ISSUE TITLE
Could this awesome work be relicensed?

### ISSUE THREAD

**Issue by xplshn** [Un1q32/uniqlibc#2]
Hi, awesome work. I was wondering if you'd be open to relicense it to a freer license that allows distributing statically linked programs with routines from your code..?
Some license candidates:
- 3BSD: Recognized and also protects the dev's rights
- MIT: Recognized, very open and unencumbered
- The Unlicense: Has its SPDX identified, tho it is not that well-known, it is equivalent to 3BSD and it is MIT-compatible. It is also a movement to push for freer code. It is used by projects like yt-dlp and others.

**Comment by Un1q32** [comment]
I close AGPLv3 because I didn't want forks to be closed source.  Why do you want a relicense?  What do you plan to do?

**Comment by xplshn** [comment]
> I close AGPLv3 because I didn't want forks to be closed source. Why do you want a relicense? What do you plan to do?

Isn't this a libc? The license forbids static linking. So, even a statically linked hello world binary that gets distributed would be forbidden.

And also, I don't thin anyone is going to make a closed source fork anytime soon. Companies usually just upstream their patches because it makes development of their products easier, pushes work off of their hands and into the hands of the upstream maintainers.

**Comment by Un1q32** [comment]
You can still distribute static binaries, but you'll need to distribute source code alongside them under AGPLv3 or a less restrictive license, for the libc and any program linking to it.

You shouldn't use this for that anyway, of the platforms it supports, the only one with a stable syscall interface is Linux, your binaries may break on newer versions of the systems, and on Linux you're better off just using musl.  Also this isn't very complete, there's still many headers in include/sys that assume Darwin constants, since this was originally only for Darwin and was only made cross platform after.  This project is primarily a toy and a learning resource (at least for now).

**Comment by xplshn** [comment]
> You can still distribute static binaries, but you'll need to distribute source code alongside them under AGPLv3 or a less restrictive license, for the libc and any program linking to it.
> 
> You shouldn't use this for that anyway, of the platforms it supports, the only one with a stable syscall interface is Linux, your binaries may break on newer versions of the systems, and on Linux you're better off just using musl. Also this isn't very complete, there's still many headers in include/sys that assume Darwin constants, since this was originally only for Darwin and was only made cross platform after. This project is primarily a toy and a learning resource (at least for now).

Shame :(

So, this is a WONTFIX?

**Comment by xplshn** [comment]
btw, the Cosmopolitan libc is also really good, and since it is licensed under a permissive license, you can benefit from it and take the source code without having to contaminate your codebase with other licenses.

It implements things like pledge() and unveil(), its an awesome resource in its `tiny` mode (which makes it work like `musl`)

**Comment by Un1q32** [comment]
There are parts that are independent of a syscall interface, like the stdio interface, that I do feel are pretty good.  If I ever get to the point where I feel those components are finished I may consider releasing them under MIT, but I still think you should just open source your programs that link to it.

**Comment by Un1q32** [comment]
Cosmopolitan has always been interesting to me, I should look into how they handle unstable syscall interfaces.  FreeBSD versions before 10 don't support the pipe2 syscall, but in FreeBSD 11 the pipe syscall was removed and made a wrapper around pipe2, this seemingly makes it impossible to support both FreeBSD 11 and 9 in the same static binary, since you can either implement pipe as a pipe2 wrapper, which won't work on FreeBSD 9, or just call the original pipe syscall, which won't work on FreeBSD 11.

**Comment by Un1q32** [comment]
I looked into it and Cosmopolitan's solution to syscall instability seems to be just to require a really recent minimum version for all non-stable platforms.
<img width="348" alt="Screenshot 2024-11-21 at 8 09 20 PM" src="https://github.com/user-attachments/assets/f2735789-49b2-4c68-8b61-0d7afa1764e8">

**Comment by xplshn** [comment]
> I looked into it and Cosmopolitan's solution to syscall instability seems to be just to require a really recent minimum version for all non-stable platforms. <img alt="Screenshot 2024-11-21 at 8 09 20 PM" width="348" src="https://private-user-images.githubusercontent.com/57970114/388754419-f2735789-49b2-4c68-8b61-0d7afa1764e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDAyODYsIm5iZiI6MTczMjIzOTk4NiwicGF0aCI6Ii81Nzk3MDExNC8zODg3NTQ0MTktZjI3MzU3ODktNDliMi00YzY4LThiNjEtMGQ3YWZhMTc2NGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAxNDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTU4NDQ0ZTAwYjhlMDVjNTE3N2NlZjYyMTdmY2U4MjZhMGJkNTM5YzM0NjFiMDY2ZTg5MTIzNzAxZmI1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FZoprJuJHFxUtq9eZ85s_ZydYnBQS3RXX9XRWU98nfE">

There's also `mlibc`, the portable POSIX libc. I don't like it because of its very intrusive license, but it is good reference.

**Comment by Un1q32** [comment]
https://github.com/managarm/mlibc/blob/master/LICENSE
Looks like MIT

**Comment by Un1q32** [comment]
fuck it e80e4f9bd63430b3e2dbbaab8277b1e10dd4e588

**Comment by xplshn** [comment]
> https://github.com/managarm/mlibc/blob/master/LICENSE Looks like MIT

Oh, my bad, I think it was managarmOS that was GPL.

Anyways, cool stuff, I learned a lot from there. And one thing I did once was port Cosmopolitan pledge(), so that I could build oBSD ports easily.

I think it'd be cool to see a complementary libc that can be used for porting software.

**Comment by Un1q32** [comment]
> Oh, my bad, I think it was managarmOS that was GPL.

https://github.com/MYRWYR/ManagarmOS/blob/master/LICENSE
nope

**Comment by xplshn** [comment]
uh
